from langchain_anthropic import ChatAnthropic
from langchain_core.messages import SystemMessage, HumanMessage
from agent.state import inject_user_prompt


class LLMInterface:
    def __init__(
        self,
        llm_provider="anthropic",
        model="claude-sonnet-4-5-20250929",
        thinking_mode: bool = False,
        max_tokens: int = 64000,
    ):
        self.model = model
        self.llm_provider = llm_provider
        self.max_tokens = max_tokens
        self._thinking_mode = (
            {"type": "enabled", "budget_tokens": 2000} if thinking_mode else None
        )
        self._cost_per_token = self._get_cost_per_token()
        self._context_window_size = self._get_context_window_size()
        self._system_prompt = None
        self._llm_client = None

    @property
    def thinking(self):
        return self._llm_client.thinking

    @thinking.setter
    def thinking(self, flag: bool):
        if flag:
            setattr(
                self._llm_client, "thinking", {"type": "enabled", "budget_tokens": 2000}
            )
        else:
            setattr(self._llm_client, "thinking", None)

    @property
    def cost_per_token(self):
        return self._cost_per_token

    @property
    def system_prompt(self):
        return self._system_prompt

    def _get_context_window_size(self):
        if self.llm_provider == "anthropic":
            if self.model == "claude-sonnet-4-5-20250929":
                return 200000

    def _get_cost_per_token(self):
        if self.llm_provider == "anthropic":
            if self.model == "claude-sonnet-4-5-20250929":
                return {
                    "input_token_cost": 3 / 1000000,
                    "output_token_cost": 15 / 1000000,
                    "cache_read_cost": 0.30 / 1000000,
                    "cache_write_cost_5m": 3.75 / 1000000,
                    "cache_write_cost_1h": 6 / 1000000,
                }

    def get_model_name(self, model_name):
        model_mapping = {"claude-sonnet-4-5-20250929": "claude sonnet 4.5"}
        return model_mapping[model_name]

    def client(self):
        # Anthropic LLM
        if self.llm_provider == "anthropic":
            self._llm_client = ChatAnthropic(
                model=self.model,
                max_tokens=self.max_tokens,
                thinking=self._thinking_mode,
            )

        return self._llm_client

    def get_system_prompt(self, user_prompt):
        self._system_prompt = inject_user_prompt(user_prompt)
        if self.llm_provider == "anthropic":
            system_prompt = SystemMessage(
                content=[
                    {
                        "type": "text",
                        "text": self._system_prompt,
                        "cache_control": {"type": "ephemeral"},
                    }
                ]
            )

        return system_prompt

    def _summary_system_prompt(self, conversation_logs):
        prompt = f"""
        You are a very experienced software engineer and your task is to generate a very high quality and detailed summary
        of the provided conversation which includes user's questions, response generated by AI model and code definitions and file paths.
        Use this information to create a rich summary highlighting important aspects of the conversation. Also remember if a summary already exists in the conversation
        then use it exactly and do not remove any insights from it rather use that information in the old summary and create a new summary of the entire conversation.

        {conversation_logs}

        ### IMPORTANT:
        - Preserve and take into consideration previous summary if available and use it to create a new summary remember all the file paths, code blocks mentioned,
          core ideas mentioned in previous summary.
        - Remember the important code file paths, code definitions present in each file path.
        - Mention all file paths as a list.
        - Mention all file paths and mention code definitions used or mentioned in conversation only names of (classes, functions or methods) in each listed file.
        - Explain important code blocks along with code definitions that were mentioned during conversation put emphasis on such code mentions.
        - Highlight and mention important insights during conversation that captures the core idea and intent of the conversation.
        - DO NOT GENERATE any new code or file paths or class, method or function names.
        - Summary should be in a proper Markdown format.

        <example>
            ## File paths:
            - src/tools/utils.py
            - src/cli/processing.py
            - src/agent/interface.py

            ## Code definitions mentioned/visited in each file path:
            - (src/tools/utils.py) - def auto_compact_context(self), def clear_session, def config
            - (src/cli/processing.py) - def bg_query_logs_processing, def bg_query_processing
            - (src/agent/interface.py) - def agent_state, def token_usage, def clear_session, class Agent

            ## Conversation Summary:
            This conversation involved a user requesting to see code examples that use the `@property` decorator.
            The AI assistant helped locate and display such code from the codebase.\n\n
            ### User Request\nThe user made a simple request to "show code with @property", seeking examples of Python property decorators in the codebase.\n\n
            ### AI Response and Analysis\n\n### Search Results\nThe AI used a grep tool to search for `@property` usage across the codebase and
                found occurrences in:\n- **`parser.py`** at line 30\n- **`main.py`** at lines 59, 63, and 67\n\n
            ### File Exploration\nThe AI discovered a comprehensive project structure with multiple modules:\n
                - `./src/code_parser/` - Contains parsing functionality\n
                -`./src/agent/` - Contains agent-related code including LLM, tools, and utilities\n
                -`./src/cli/` - Contains command-line interface components\n\n
        </example>
        """

        return prompt

    def generate_summary(self, messages):
        prompt = self._summary_system_prompt(messages)

        system_prompt = SystemMessage(content=prompt)

        messages = [
            system_prompt,
            HumanMessage(content="Generate a detailed summary of the conversation."),
        ]

        llm_client = self.client()
        summary_response = llm_client.invoke(messages)

        return summary_response
